name: incisive
description: "The app of the INCISIVE project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  pine: ^1.0.4
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  http: ^1.6.0
  provider: ^6.1.2
  equatable: ^2.0.7
  supabase: ^2.10.0
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.12.0
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: any
  logger: ^2.6.2
  file_picker: ^10.3.7
  email_validator: ^2.1.17
  easy_date_timeline: ^2.0.9
  skeletonizer: ^2.1.1
  syncfusion_flutter_gauges: ^31.2.16
  lottie: ^3.3.2
  flame: ^1.34.0
  flame_lottie: ^0.4.2+18
  speech_to_text: ^7.3.0
  chat_bubbles: ^1.7.0
  go_router: ^17.0.1
  flutter_dotenv: ^6.0.0
  flutter_markdown_plus: ^1.0.7
  fl_chart: ^1.1.1

  flutter_localizations:
    sdk: flutter
  tutorial_coach_mark: ^1.2.12
  shared_preferences: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/NunitoSans_10pt-Bold.ttf

flutter_native_splash:
  color: "#8D5A23"
  image: assets/images/logo_white.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#8D5A23"
    image: assets/images/logo_white_12.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#8D5A23"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 21